packages:
  - "core-free"
  - "core-ai-prompts"
  - "core-project-portfolio"
  - "pro-excel"
  - "pro-e-commerce"
  - "pro-project-table"
  - "pro-construction-operations"
  - "pro-construction-gantt-simple"
  - "pro-advanced-planning"
  - "pro-filtering"
  - "pro-tree-data"
  - "pro-infinity-scroll"
  - "pro-column-collapse"
  - "pro-data-grid-context-menu"
  - "pro-row-master"
  - "pro-audit-history"
minimumReleaseAgeExclude:
  - '@revolist/angular-datagrid@4.28.0'
  - '@revolist/gantt-trial@2.9.4'
  - '@revolist/kanban-trial@2.9.4'
  - '@revolist/react-datagrid@4.28.0'
  - '@revolist/revogrid-column-date@2.0.27'
  - '@revolist/revogrid@4.28.0'
  - '@revolist/rv-pro-trial@2.9.4'
  - '@revolist/scheduler-trial@2.9.4'
  - '@revolist/svelte-datagrid@4.28.0'
  - '@revolist/vue3-datagrid@4.28.0'
