packages:
  - "core-free"
  - "pro-excel"
  - "pro-e-commerce"
  - "pro-project-table"
  - "pro-advanced-planning"
  - "pro-filtering"
  - "pro-tree-data"
  - "pro-infinity-scroll"
  - "pro-column-collapse"
  - "pro-row-master"
  - "pro-audit-history"
