import { WEEK_DATES } from './color.utils';

// set tags for color showcase
export const TAGS = [
  { label: 'Frontend', value: 'Frontend' },
  { label: 'Backend', value: 'Backend' },
  { label: 'Design', value: 'Design' },
  { label: 'QA', value: 'QA' },
  { label: 'React', value: 'React' },
  { label: 'Vue', value: 'Vue' },
  { label: 'Angular', value: 'Angular' },
  { label: 'Node.js', value: 'Node.js' },
  { label: 'Python', value: 'Python' },
  { label: 'Java', value: 'Java' },
  { label: 'C#', value: 'C#' },
  { label: 'Ruby', value: 'Ruby' },
  { label: 'PHP', value: 'PHP' },
  { label: 'Other', value: 'Other' },
];

// set priority for color showcase
export const PRIORITY = [
  {
    label: 'High',
    value: 'High',
    color: '#e2435c',
  },
  {
    label: 'Medium',
    value: 'Medium',
    color: '#f7c605',
  },
  {
    label: 'Low',
    value: 'Low',
    color: '#00c874',
  },
];

// set status for color showcase
export const STATUS = [
  { label: 'In Progress', value: 'In Progress', color: '#f7c605' },
  { label: 'Complete', value: 'Complete', color: '#00c874' },
  { label: 'Not Started', value: 'Not Started', color: '#e2435c' },
];

// set data for color showcase
export const DATA_COLOR = [
  {
    name: 'John Doe',
    avatar: `https://randomuser.me/api/portraits/men/1.jpg`,
    priority: 'High',
    status: 'In Progress',
    progress: 20,
    timeline: { from: '2024-03-20', to: '2024-03-27' },
    budget: 15000,
    tags: ['Frontend', 'React', 'Vue'],
    links: ['https://github.com', 'https://docs.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Convince AI to write better code than humans',
  },
  {
    name: 'Jane Smith',
    avatar: `https://randomuser.me/api/portraits/women/2.jpg`,
    priority: 'Medium',
    status: 'Not Started',
    timeline: { from: '2024-03-28', to: '2024-04-04' },
    budget: 8000,
    tags: ['Backend', 'Node.js'],
    links: ['https://api.example.com'],
    progress: 50,
    week: WEEK_DATES.nextWeek,
    task: 'Teach rubber duck to debug code',
  },
  {
    name: 'Bob Johnson',
    avatar: `https://randomuser.me/api/portraits/men/3.jpg`,
    priority: 'Medium',
    status: 'Complete',
    progress: 40,
    timeline: { from: '2024-04-05', to: '2024-04-12' },
    budget: 5000,
    tags: ['Design', 'UI/UX'],
    links: ['https://design.example.com'],
    todo: 'Completed',
    week: WEEK_DATES.previousWeek,
    task: 'Make coffee machine understand TypeScript',
  },
  {
    name: 'John Doe',
    avatar: `https://randomuser.me/api/portraits/men/5.jpg`,
    priority: 'Medium',
    status: 'Complete',
    timeline: { from: '2024-03-20', to: '2024-03-27' },
    budget: 15000,
    tags: ['Frontend', 'React', 'Vue'],
    links: ['https://github.com', 'https://docs.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Convert office plants to React components',
    progress: 50,
  },
  {
    name: 'Jane Smith',
    avatar: `https://randomuser.me/api/portraits/men/3.jpg`,
    priority: 'Medium',
    status: 'Complete',
    timeline: { from: '2024-03-28', to: '2024-04-04' },
    budget: 8000,
    tags: ['Backend', 'Node.js'],
    links: ['https://api.example.com'],
    week: WEEK_DATES.nextWeek,
    task: 'Train office cat to catch bugs',
    progress: 30,
  },
  {
    name: 'Bob Johnson',
    avatar: `https://randomuser.me/api/portraits/women/4.jpg`,
    priority: 'High',
    status: 'Complete',
    timeline: { from: '2024-04-05', to: '2024-04-12' },
    budget: 5000,
    tags: ['Design', 'UI/UX'],
    links: ['https://design.example.com'],
    week: WEEK_DATES.previousWeek,
    task: 'Make printer understand JSON',
    progress: 5,
  },
  {
    name: 'John Doe',
    avatar: `https://randomuser.me/api/portraits/women/4.jpg`,
    priority: 'Low',
    status: 'In Progress',
    timeline: { from: '2024-03-20', to: '2024-03-27' },
    progress: 100,
    budget: 15000,
    tags: ['Frontend', 'React', 'Vue'],
    links: ['https://github.com', 'https://docs.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Humans: 1, Code: 0!',
  },
  {
    name: 'Alice Brown',
    avatar: `https://randomuser.me/api/portraits/women/5.jpg`,
    priority: 'High',
    status: 'In Progress',
    timeline: { from: '2024-04-13', to: '2024-04-20' },
    budget: 12000,
    tags: ['Frontend', 'Vue', 'Design'],
    links: ['https://portfolio.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Redesign the company website',
    progress: 40,
  },
  {
    name: 'Charlie Davis',
    avatar: `https://randomuser.me/api/portraits/men/6.jpg`,
    priority: 'Medium',
    status: 'Complete',
    timeline: { from: '2024-04-21', to: '2024-04-28' },
    budget: 7000,
    tags: ['Backend', 'Node.js', 'API'],
    links: ['https://api.example.com'],
    week: WEEK_DATES.nextWeek,
    task: 'Develop new API endpoints',
    progress: 100,
  },
  {
    name: 'Eve White',
    avatar: `https://randomuser.me/api/portraits/women/6.jpg`,
    priority: 'Low',
    status: 'In Progress',
    timeline: { from: '2024-04-29', to: '2024-05-06' },
    budget: 5000,
    tags: ['Testing', 'QA'],
    links: ['https://testing.example.com'],
    week: WEEK_DATES.previousWeek,
    task: 'Conduct user acceptance testing',
    progress: 20,
  },
  {
    name: 'David Wilson',
    avatar: `https://randomuser.me/api/portraits/men/7.jpg`,
    priority: 'High',
    status: 'Complete',
    timeline: { from: '2024-05-07', to: '2024-05-14' },
    budget: 15000,
    tags: ['DevOps', 'Infrastructure'],
    links: ['https://devops.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Migrate to cloud infrastructure',
    progress: 100,
  },
  {
    name: 'Grace Lee',
    avatar: `https://randomuser.me/api/portraits/women/7.jpg`,
    priority: 'Medium',
    status: 'In Progress',
    timeline: { from: '2024-05-15', to: '2024-05-22' },
    budget: 9000,
    tags: ['Frontend', 'React', 'UI/UX'],
    links: ['https://uiux.example.com'],
    week: WEEK_DATES.nextWeek,
    task: 'Create a new user dashboard',
    progress: 60,
  },
  {
    name: 'Henry Martinez',
    avatar: `https://randomuser.me/api/portraits/men/8.jpg`,
    priority: 'Low',
    status: 'Complete',
    timeline: { from: '2024-05-23', to: '2024-05-30' },
    budget: 3000,
    tags: ['Documentation'],
    links: ['https://docs.example.com'],
    week: WEEK_DATES.previousWeek,
    task: 'Update project documentation',
    progress: 100,
  },
  {
    name: 'Isabella Garcia',
    avatar: `https://randomuser.me/api/portraits/women/8.jpg`,
    priority: 'High',
    status: 'In Progress',
    timeline: { from: '2024-06-01', to: '2024-06-08' },
    budget: 11000,
    tags: ['Marketing', 'SEO'],
    links: ['https://marketing.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Launch new marketing campaign',
    progress: 30,
  },
  {
    name: 'Jack Thompson',
    avatar: `https://randomuser.me/api/portraits/men/9.jpg`,
    priority: 'Medium',
    status: 'Complete',
    timeline: { from: '2024-06-09', to: '2024-06-16' },
    budget: 8000,
    tags: ['Data Science', 'Analytics'],
    links: ['https://analytics.example.com'],
    week: WEEK_DATES.nextWeek,
    task: 'Analyze user data for insights',
    progress: 100,
  },
  {
    name: 'Liam Johnson',
    avatar: `https://randomuser.me/api/portraits/men/10.jpg`,
    priority: 'Low',
    status: 'In Progress',
    timeline: { from: '2024-06-17', to: '2024-06-24' },
    budget: 4000,
    tags: ['Support', 'Customer Service'],
    links: ['https://support.example.com'],
    week: WEEK_DATES.previousWeek,
    task: 'Improve customer support response time',
    progress: 50,
  },
  {
    name: 'Mia Robinson',
    avatar: `https://randomuser.me/api/portraits/women/9.jpg`,
    priority: 'High',
    status: 'Complete',
    timeline: { from: '2024-06-25', to: '2024-07-02' },
    budget: 13000,
    tags: ['Product', 'Management'],
    links: ['https://product.example.com'],
    week: WEEK_DATES.thisWeek,
    task: 'Define product roadmap for next quarter',
    progress: 100,
  },
];
